#!/usr/bin/env python3
"""
Web后端服务
提供REST API和WebSocket实时通信
"""
import json
import asyncio
import threading
from datetime import datetime
from pathlib import Path
from flask import Flask, jsonify, request, send_from_directory
from flask_cors import CORS

# 尝试导入WebSocket支持
try:
    from flask_sock import Sock
    WS_AVAILABLE = True
except ImportError:
    WS_AVAILABLE = False
    print("警告: flask-sock 未安装，WebSocket功能不可用")

app = Flask(__name__)
CORS(app)

if WS_AVAILABLE:
    sock = Sock(app)

# 全局状态存储
system_state = {
    'total_nodes': 0,
    'total_people': 0,
    'energy_saved': 0.0,
    'cpu_usage': 0,
    'mem_usage': 0,
    'corridor': {
        'light_on': False,
        'people_count': 0,
        'brightness': 0,
        'on_count': 0,
        'on_time': 0,
        'energy_saved': 0
    },
    'classroom': {
        'ac_on': False,
        'target_temp': 26,
        'people_count': 0,
        'zones': {}
    },
    'nodes': []
}

# WebSocket连接池
ws_clients = set()


def broadcast_message(message_type: str, payload: dict):
    """广播消息到所有WebSocket客户端"""
    if not WS_AVAILABLE:
        return
    
    message = json.dumps({
        'type': message_type,
        'timestamp': datetime.now().isoformat(),
        'payload': payload
    })
    
    # 存储到全局状态
    if message_type in system_state:
        system_state[message_type].update(payload)
    
    # 发送给所有客户端
    disconnected = set()
    for client in ws_clients:
        try:
            client.send(message)
        except:
            disconnected.add(client)
    
    # 清理断开的连接
    ws_clients -= disconnected


@app.route('/')
def index():
    """主页"""
    return send_from_directory('web', 'index.html')


@app.route('/web/<path:path>')
def serve_web(path):
    """静态文件"""
    return send_from_directory('web', path)


# ==================== API路由 ====================

@app.route('/api/status')
def get_status():
    """获取系统整体状态"""
    return jsonify({
        'total_nodes': system_state['total_nodes'],
        'total_people': system_state['total_people'],
        'energy_saved': system_state['energy_saved'],
        'cpu_usage': system_state['cpu_usage'],
        'mem_usage': system_state['mem_usage'],
        'timestamp': datetime.now().isoformat()
    })


@app.route('/api/corridor/status')
def get_corridor_status():
    """获取楼道灯状态"""
    return jsonify(system_state['corridor'])


@app.route('/api/corridor/control', methods=['POST'])
def control_corridor():
    """控制楼道灯"""
    data = request.json
    action = data.get('action')
    
    if action == 'on':
        system_state['corridor']['light_on'] = True
        broadcast_message('corridor', {'light_on': True})
    elif action == 'off':
        system_state['corridor']['light_on'] = False
        broadcast_message('corridor', {'light_on': False})
    elif action == 'auto':
        # 切换到自动模式
        pass
    
    return jsonify({'success': True, 'action': action})


@app.route('/api/classroom/status')
def get_classroom_status():
    """获取教室空调状态"""
    return jsonify(system_state['classroom'])


@app.route('/api/classroom/control', methods=['POST'])
def control_classroom():
    """控制教室空调"""
    data = request.json
    action = data.get('action')
    
    if action == 'on':
        system_state['classroom']['ac_on'] = True
    elif action == 'off':
        system_state['classroom']['ac_on'] = False
    
    broadcast_message('classroom', system_state['classroom'])
    return jsonify({'success': True, 'action': action})


@app.route('/api/classroom/temp', methods=['POST'])
def set_classroom_temp():
    """设置空调温度"""
    data = request.json
    temp = data.get('temperature', 26)
    system_state['classroom']['target_temp'] = temp
    
    broadcast_message('classroom', {'target_temp': temp})
    return jsonify({'success': True, 'temperature': temp})


@app.route('/api/nodes')
def get_nodes():
    """获取所有节点"""
    return jsonify({'nodes': system_state['nodes']})


@app.route('/api/nodes/discover', methods=['POST'])
def discover_nodes():
    """发现新节点"""
    # 实际实现中扫描网络或MQTT
    return jsonify({'success': True, 'message': '节点发现已启动'})


@app.route('/api/nodes/rebalance', methods=['POST'])
def rebalance_nodes():
    """负载均衡"""
    return jsonify({'success': True, 'message': '负载均衡已执行'})


@app.route('/api/reports/daily')
def get_daily_report():
    """获取日报"""
    report = f"""# 每日能耗报告 - {datetime.now().strftime('%Y-%m-%d')}

## 总体统计
- 在线节点: {system_state['total_nodes']}
- 总检测人数: {system_state['total_people']}
- 节电量: {system_state['energy_saved']:.2f} kWh

## 楼道灯
- 开灯次数: {system_state['corridor']['on_count']}
- 开灯时长: {system_state['corridor']['on_time'] / 60:.1f} 分钟

## 教室空调
- 运行时间: 计算中...
- 平均人数: {system_state['classroom']['people_count']}

---
*Generated by Smart Energy System*
"""
    return report, 200, {'Content-Type': 'text/markdown'}


@app.route('/api/data/export')
def export_data():
    """导出数据"""
    return jsonify(system_state)


# ==================== WebSocket ====================

if WS_AVAILABLE:
    @sock.route('/ws')
    def websocket(ws):
        """WebSocket连接处理"""
        ws_clients.add(ws)
        print(f"WebSocket客户端已连接，当前连接数: {len(ws_clients)}")
        
        try:
            # 发送初始状态
            ws.send(json.dumps({
                'type': 'status',
                'payload': {
                    'total_nodes': system_state['total_nodes'],
                    'total_people': system_state['total_people'],
                    'energy_saved': system_state['energy_saved'],
                    'cpu_usage': system_state['cpu_usage'],
                    'mem_usage': system_state['mem_usage']
                }
            }))
            
            # 保持连接
            while True:
                try:
                    message = ws.receive(timeout=30)
                    if message:
                        # 处理客户端消息
                        data = json.loads(message)
                        handle_client_message(ws, data)
                except:
                    break
        
        finally:
            ws_clients.discard(ws)
            print(f"WebSocket客户端已断开，当前连接数: {len(ws_clients)}")


def handle_client_message(ws, data):
    """处理客户端消息"""
    msg_type = data.get('type')
    
    if msg_type == 'ping':
        ws.send(json.dumps({'type': 'pong'}))
    elif msg_type == 'subscribe':
        # 订阅特定主题
        pass


# ==================== 状态更新模拟 ====================

def start_status_simulation():
    """启动状态模拟（实际部署时替换为真实数据）"""
    import random
    
    def simulate():
        while True:
            # 模拟数据变化
            system_state['cpu_usage'] = random.randint(10, 60)
            system_state['mem_usage'] = random.randint(30, 70)
            system_state['total_people'] = random.randint(0, 20)
            system_state['corridor']['brightness'] = random.randint(30, 200)
            system_state['corridor']['people_count'] = random.randint(0, 3)
            system_state['classroom']['people_count'] = random.randint(0, 15)
            
            # 广播更新
            broadcast_message('status', {
                'cpu_usage': system_state['cpu_usage'],
                'mem_usage': system_state['mem_usage'],
                'total_people': system_state['total_people']
            })
            
            import time
            time.sleep(2)
    
    thread = threading.Thread(target=simulate, daemon=True)
    thread.start()


def run_server(host='0.0.0.0', port=5000, debug=False):
    """运行服务器"""
    # 启动模拟（测试用）
    start_status_simulation()
    
    print(f"启动Web服务器: http://{host}:{port}")
    app.run(host=host, port=port, debug=debug, use_reloader=False)


if __name__ == '__main__':
    run_server()
